// AUTO-GENERATED by scripts/gen-schemas.mjs — do not edit.
// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse the JSON, add this file to your project and do:
//
//   let adapterConfig = try AdapterConfig(json)

import Foundation

/// Per-platform credential block. Discriminated by `platform`. Other config (vault path,
/// sync folder, conflict strategy, …) stays in the top-level DaemonConfig — these fields are
/// purely the CMS connection.
// MARK: - AdapterConfig
public struct AdapterConfig: Equatable {
    public let adminAPIKey, ghostURL: String?
    public let platform: Platform
    /// Admin API access token (shpat_… for dev-store, OAuth token in prod).
    ///
    /// OAuth access token (PRO). Issued by the hosted OAuth flow
    /// (`web/src/pages/api/oauth/webflow/`). Webflow OAuth tokens are long-lived and
    /// non-expiring with no refresh token, so this is simply another bearer token — used in
    /// preference to `apiToken`. The adapter never branches on which produced the token. At
    /// least one of `apiToken` / `accessToken` must be present.
    public let accessToken: String?
    /// ISO timestamp when the access token expires.
    public let accessTokenExpiresAt: String?
    /// GraphQL API version. Defaults to the adapter's pinned version.
    public let apiVersion: String?
    /// OAuth refresh token for expiring offline tokens. Rotated after every refresh.
    public let refreshToken: String?
    /// ISO timestamp when the refresh token expires.
    public let refreshTokenExpiresAt: String?
    /// Full myshopify.com domain, e.g. "my-store.myshopify.com".
    public let shop: String?
    /// Application Password — 24-char string (spaces stripped internally).
    public let appPassword: String?
    /// Full URL of the WordPress site, e.g. "https://myblog.com".
    public let siteURL: String?
    /// WordPress username.
    public let username: String?
    /// Site API token (Bearer) — the AGPL/DIY auth path. Paste a token from the site's API
    /// access settings.
    public let apiToken: String?
    /// Optional per-collection field-mapping overrides, keyed by collection id. Omitted fields
    /// fall back to auto-detection (name → title, slug → slug, first RichText field → body).
    public let fieldMap: [String: FieldMap]?
    /// Webflow site ID whose CMS collections are synced.
    public let siteID: String?

    public init(adminAPIKey: String?, ghostURL: String?, platform: Platform, accessToken: String?, accessTokenExpiresAt: String?, apiVersion: String?, refreshToken: String?, refreshTokenExpiresAt: String?, shop: String?, appPassword: String?, siteURL: String?, username: String?, apiToken: String?, fieldMap: [String: FieldMap]?, siteID: String?) {
        self.adminAPIKey = adminAPIKey
        self.ghostURL = ghostURL
        self.platform = platform
        self.accessToken = accessToken
        self.accessTokenExpiresAt = accessTokenExpiresAt
        self.apiVersion = apiVersion
        self.refreshToken = refreshToken
        self.refreshTokenExpiresAt = refreshTokenExpiresAt
        self.shop = shop
        self.appPassword = appPassword
        self.siteURL = siteURL
        self.username = username
        self.apiToken = apiToken
        self.fieldMap = fieldMap
        self.siteID = siteID
    }
}

// MARK: - FieldMap
public struct FieldMap: Equatable {
    public let body, slug, tags, title: String?

    public init(body: String?, slug: String?, tags: String?, title: String?) {
        self.body = body
        self.slug = slug
        self.tags = tags
        self.title = title
    }
}

public enum Platform: String, Equatable {
    case ghost
    case shopify
    case webflow
    case wordpress
}
