// AUTO-GENERATED by scripts/gen-schemas.mjs — do not edit.
// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse the JSON, add this file to your project and do:
//
//   let adapterConfig = try AdapterConfig(json)

import Foundation

/// Per-platform credential block. Discriminated by `platform`. Other config (vault path,
/// sync folder, conflict strategy, …) stays in the top-level DaemonConfig — these fields are
/// purely the CMS connection.
// MARK: - AdapterConfig
public struct AdapterConfig: Equatable {
    public let adminAPIKey, ghostURL: String?
    public let platform: Platform
    /// Admin API access token (shpat_… for dev-store, OAuth token in prod).
    public let accessToken: String?
    /// ISO timestamp when the access token expires.
    public let accessTokenExpiresAt: String?
    /// GraphQL API version. Defaults to the adapter's pinned version.
    public let apiVersion: String?
    /// OAuth refresh token for expiring offline tokens. Rotated after every refresh.
    public let refreshToken: String?
    /// ISO timestamp when the refresh token expires.
    public let refreshTokenExpiresAt: String?
    /// Full myshopify.com domain, e.g. "my-store.myshopify.com".
    public let shop: String?
    /// Application Password — 24-char string (spaces stripped internally).
    public let appPassword: String?
    /// Full URL of the WordPress site, e.g. "https://myblog.com".
    public let siteURL: String?
    /// WordPress username.
    public let username: String?

    public init(adminAPIKey: String?, ghostURL: String?, platform: Platform, accessToken: String?, accessTokenExpiresAt: String?, apiVersion: String?, refreshToken: String?, refreshTokenExpiresAt: String?, shop: String?, appPassword: String?, siteURL: String?, username: String?) {
        self.adminAPIKey = adminAPIKey
        self.ghostURL = ghostURL
        self.platform = platform
        self.accessToken = accessToken
        self.accessTokenExpiresAt = accessTokenExpiresAt
        self.apiVersion = apiVersion
        self.refreshToken = refreshToken
        self.refreshTokenExpiresAt = refreshTokenExpiresAt
        self.shop = shop
        self.appPassword = appPassword
        self.siteURL = siteURL
        self.username = username
    }
}

public enum Platform: String, Equatable {
    case ghost
    case shopify
    case wordpress
}
