// AUTO-GENERATED by scripts/gen-schemas.mjs — do not edit.
// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse the JSON, add this file to your project and do:
//
//   let daemonConfig = try DaemonConfig(json)

import Foundation

// MARK: - DaemonConfig
public struct DaemonConfig: Equatable {
    public let adminAPIKey: String
    public let conflictStrategy: ConflictStrategy
    public let ghostURL: String
    public let pullDrafts, pullPublished: Bool
    public let syncFolderPath: String
    /// How the watcher reacts to local file edits.
    /// - 'auto'   (default): push changes within the debounce window; periodic full sync.
    /// - 'manual': watcher only runs periodic pulls; pushes are user-driven via Sync Now /
    /// Push to Ghost. Lets cautious users avoid surprise writes to their blog.
    public let syncMode: SyncMode
    /// Multi-target list. Always present after `loadConfig()` (synthesized from legacy fields if
    /// absent on disk). Always written to disk by `saveConfig`.
    public let targets: [TargetConfig]
    /// Absolute path to the vault root.
    public let vaultPath: String
    /// Debounce window (ms) for the file watcher before flushing changes.
    public let watchDebounceMS: Double

    public init(adminAPIKey: String, conflictStrategy: ConflictStrategy, ghostURL: String, pullDrafts: Bool, pullPublished: Bool, syncFolderPath: String, syncMode: SyncMode, targets: [TargetConfig], vaultPath: String, watchDebounceMS: Double) {
        self.adminAPIKey = adminAPIKey
        self.conflictStrategy = conflictStrategy
        self.ghostURL = ghostURL
        self.pullDrafts = pullDrafts
        self.pullPublished = pullPublished
        self.syncFolderPath = syncFolderPath
        self.syncMode = syncMode
        self.targets = targets
        self.vaultPath = vaultPath
        self.watchDebounceMS = watchDebounceMS
    }
}

public enum ConflictStrategy: String, Equatable {
    case ask
    case keepLocal
    case keepRemote
}

/// How the watcher reacts to local file edits.
/// - 'auto'   (default): push changes within the debounce window; periodic full sync.
/// - 'manual': watcher only runs periodic pulls; pushes are user-driven via Sync Now /
/// Push to Ghost. Lets cautious users avoid surprise writes to their blog.
public enum SyncMode: String, Equatable {
    case auto
    case manual
}

/// Per-target configuration: one CMS connection + the engine-visible sync settings that
/// govern how its content lives in the vault.
///
/// v0.4.0 Phase B introduces this as the canonical unit; legacy single-Ghost configs (every
/// shipped user) auto-synthesize a single `targets[0]` on load via `synthesizeLegacyTarget`.
/// The writer still emits the legacy flat fields alongside `targets[]` for one release
/// window so a downgrade is non-fatal.
// MARK: - TargetConfig
public struct TargetConfig: Equatable {
    /// CMS credentials. Discriminated by `platform`.
    public let adapter: AdapterConfig
    public let conflictStrategy: ConflictStrategy
    /// URL-safe handle — also the folder name when multiple targets are configured.
    public let handle: String
    /// Display label, e.g. "My Ghost Blog".
    public let label: String
    public let pullDrafts, pullPublished: Bool
    /// Subfolder under the target's effective root. Empty means the effective root itself is
    /// used. In single-target configs, this collapses to the legacy `syncFolderPath` behavior.
    public let syncFolderPath: String
    public let syncMode: SyncMode

    public init(adapter: AdapterConfig, conflictStrategy: ConflictStrategy, handle: String, label: String, pullDrafts: Bool, pullPublished: Bool, syncFolderPath: String, syncMode: SyncMode) {
        self.adapter = adapter
        self.conflictStrategy = conflictStrategy
        self.handle = handle
        self.label = label
        self.pullDrafts = pullDrafts
        self.pullPublished = pullPublished
        self.syncFolderPath = syncFolderPath
        self.syncMode = syncMode
    }
}

/// CMS credentials. Discriminated by `platform`.
///
/// Per-platform credential block. Discriminated by `platform`. Other config (vault path,
/// sync folder, conflict strategy, …) stays in the top-level DaemonConfig — these fields are
/// purely the CMS connection.
// MARK: - AdapterConfig
public struct AdapterConfig: Equatable {
    public let adminAPIKey, ghostURL: String?
    public let platform: Platform
    /// Admin API access token (shpat_… for dev-store, OAuth token in prod).
    public let accessToken: String?
    /// ISO timestamp when the access token expires.
    public let accessTokenExpiresAt: String?
    /// GraphQL API version. Defaults to the adapter's pinned version.
    public let apiVersion: String?
    /// OAuth refresh token for expiring offline tokens. Rotated after every refresh.
    public let refreshToken: String?
    /// ISO timestamp when the refresh token expires.
    public let refreshTokenExpiresAt: String?
    /// Full myshopify.com domain, e.g. "my-store.myshopify.com".
    public let shop: String?
    /// Application Password — 24-char string (spaces stripped internally).
    public let appPassword: String?
    /// Full URL of the WordPress site, e.g. "https://myblog.com".
    public let siteURL: String?
    /// WordPress username.
    public let username: String?

    public init(adminAPIKey: String?, ghostURL: String?, platform: Platform, accessToken: String?, accessTokenExpiresAt: String?, apiVersion: String?, refreshToken: String?, refreshTokenExpiresAt: String?, shop: String?, appPassword: String?, siteURL: String?, username: String?) {
        self.adminAPIKey = adminAPIKey
        self.ghostURL = ghostURL
        self.platform = platform
        self.accessToken = accessToken
        self.accessTokenExpiresAt = accessTokenExpiresAt
        self.apiVersion = apiVersion
        self.refreshToken = refreshToken
        self.refreshTokenExpiresAt = refreshTokenExpiresAt
        self.shop = shop
        self.appPassword = appPassword
        self.siteURL = siteURL
        self.username = username
    }
}

public enum Platform: String, Equatable {
    case ghost
    case shopify
    case wordpress
}
