// AUTO-GENERATED by scripts/gen-schemas.mjs — do not edit.
// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse the JSON, add this file to your project and do:
//
//   let postFrontmatter = try PostFrontmatter(json)

import Foundation

/// Union of both shapes — what the parser must accept during the deprecation window. Either
/// `cms` block OR `ghost_*` keys must be present for a file to be considered tracked; bare
/// files have neither and are pending push.
///
/// Legacy v1 frontmatter — flat `ghost_*` keys. Currently the only shape on disk.
///
/// V2 frontmatter — namespaced `cms` block. Written by v0.4.0+; readable by v0.3.2+.
/// Top-level user fields (`tags`, `feature_image`, `excerpt`, `local_updated_at`) keep their
/// current location.
// MARK: - PostFrontmatter
public struct PostFrontmatter: Equatable {
    public let excerpt, featureImage: String?
    public let ghostID, ghostSlug: String?
    public let ghostStatus: Status?
    public let ghostUpdatedAt: String?
    public let localUpdatedAt: String?
    public let tags: [String]
    public let cms: CMS?

    public init(excerpt: String?, featureImage: String?, ghostID: String?, ghostSlug: String?, ghostStatus: Status?, ghostUpdatedAt: String?, localUpdatedAt: String?, tags: [String], cms: CMS?) {
        self.excerpt = excerpt
        self.featureImage = featureImage
        self.ghostID = ghostID
        self.ghostSlug = ghostSlug
        self.ghostStatus = ghostStatus
        self.ghostUpdatedAt = ghostUpdatedAt
        self.localUpdatedAt = localUpdatedAt
        self.tags = tags
        self.cms = cms
    }
}

// MARK: - CMS
public struct CMS: Equatable {
    /// Native ID from the CMS — opaque to the daemon.
    public let id: String
    public let platform: Platform
    public let slug: String
    public let status: Status
    public let updatedAt: String

    public init(id: String, platform: Platform, slug: String, status: Status, updatedAt: String) {
        self.id = id
        self.platform = platform
        self.slug = slug
        self.status = status
        self.updatedAt = updatedAt
    }
}

public enum Platform: String, Equatable {
    case ghost
    case shopify
}

public enum Status: String, Equatable {
    case draft
    case published
    case scheduled
}
