#!/usr/bin/env node
/**
 * Schema codegen pipeline (v0.3.1).
 *
 *  TS source-of-truth (`src/schema/index.ts`)
 *     │
 *     ├──► JSON Schema   (ts-json-schema-generator)  →  schemas/*.json
 *     │
 *     └──► Swift structs (quicktype-core)            →  mac/Sources/Specter/Generated/*.swift
 *
 * Run:
 *   npm run schema:gen     # regenerate artifacts
 *   npm run schema:check   # regen + fail if anything differs from committed
 *
 * The CI workflow runs `schema:check` to enforce that TS and the committed
 * artifacts cannot drift apart.
 */

import { createGenerator } from 'ts-json-schema-generator';
import {
  quicktype,
  InputData,
  JSONSchemaInput,
  FetchingJSONSchemaStore,
} from 'quicktype-core';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SCHEMA_DIR = path.join(ROOT, 'schemas');
// Swift reference structs live OUTSIDE mac/Sources so SPM doesn't pick them
// up (the hand-written Config.swift owns the Codable + decodeIfPresent logic
// for shipped users; we use the generated file purely as a drift detector
// and review aid until v0.4.0 swaps it in as the real source).
const SWIFT_OUT_DIR = path.join(ROOT, 'schemas', 'swift');

const TYPES_TO_SCHEMA = [
  { name: 'DaemonConfig', file: 'config.schema.json' },
  { name: 'DaemonState', file: 'state.schema.json' },
  { name: 'AdapterConfig', file: 'adapter-config.schema.json' },
  { name: 'PostFrontmatterV1', file: 'frontmatter-v1.schema.json' },
  { name: 'PostFrontmatterV2', file: 'frontmatter-v2.schema.json' },
  { name: 'PostFrontmatterAny', file: 'frontmatter.schema.json' },
];

// Swift reference targets. Emit `.swift` extension so editors highlight them
// as Swift, but they live under schemas/swift/ so SPM does not compile them.
// The CI diff check catches when the TS shape changes without a regen.
const SWIFT_TARGETS = [
  { schemaFile: 'config.schema.json', name: 'DaemonConfig', out: 'DaemonConfig.swift' },
  {
    schemaFile: 'frontmatter.schema.json',
    name: 'PostFrontmatter',
    out: 'PostFrontmatter.swift',
  },
  {
    schemaFile: 'adapter-config.schema.json',
    name: 'AdapterConfig',
    out: 'AdapterConfig.swift',
  },
];

const HEADER = '// AUTO-GENERATED by scripts/gen-schemas.mjs — do not edit.\n';

async function generateJsonSchemas() {
  const generator = createGenerator({
    path: path.join(ROOT, 'src', 'schema', 'index.ts'),
    tsconfig: path.join(ROOT, 'tsconfig.json'),
    type: '*',
    skipTypeCheck: true,
    expose: 'export',
    topRef: true,
    jsDoc: 'extended',
    additionalProperties: false,
  });

  await fs.mkdir(SCHEMA_DIR, { recursive: true });
  const written = [];
  for (const { name, file } of TYPES_TO_SCHEMA) {
    const schema = generator.createSchema(name);
    const json = JSON.stringify(schema, null, 2) + '\n';
    const out = path.join(SCHEMA_DIR, file);
    await fs.writeFile(out, json, 'utf8');
    written.push(path.relative(ROOT, out));
  }
  return written;
}

async function generateSwift() {
  await fs.mkdir(SWIFT_OUT_DIR, { recursive: true });
  const written = [];
  for (const { schemaFile, name, out } of SWIFT_TARGETS) {
    const raw = await fs.readFile(path.join(SCHEMA_DIR, schemaFile), 'utf8');
    const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
    await input.addSource({ name, schema: raw });
    const inputData = new InputData();
    inputData.addInput(input);
    const { lines } = await quicktype({
      inputData,
      lang: 'swift',
      rendererOptions: {
        'just-types': 'true',
        'access-level': 'public',
        'protocol': 'equatable',
      },
    });
    const body = HEADER + lines.join('\n') + (lines[lines.length - 1] === '' ? '' : '\n');
    const outPath = path.join(SWIFT_OUT_DIR, out);
    await fs.writeFile(outPath, body, 'utf8');
    written.push(path.relative(ROOT, outPath));
  }
  return written;
}

const main = async () => {
  console.log('Generating JSON Schemas…');
  const jsonFiles = await generateJsonSchemas();
  jsonFiles.forEach((f) => console.log('  ' + f));

  console.log('\nGenerating Swift structs…');
  const swiftFiles = await generateSwift();
  swiftFiles.forEach((f) => console.log('  ' + f));

  console.log('\nDone.');
};

main().catch((err) => {
  console.error('Schema generation failed:', err);
  process.exit(1);
});
