#!/usr/bin/env bash
# Boot a throwaway WordPress, install it, create an Application Password,
# and write credentials to scripts/wp-dev/.env.wp-dev for use with:
#
#   ghost-sync test --platform wordpress \
#     --site-url $WP_SITE_URL --username $WP_USERNAME --app-password "$WP_APP_PASSWORD"
#
# Re-runnable: detects an existing install and skips re-init.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

HOST_PORT="${WP_HOST_PORT:-8088}"
SITE_URL="http://localhost:${HOST_PORT}"
ADMIN_USER="${WP_ADMIN_USER:-specter}"
ADMIN_PASS="${WP_ADMIN_PASS:-specter-dev-pass}"
ADMIN_EMAIL="${WP_ADMIN_EMAIL:-specter-dev@example.com}"
ENV_FILE="$HERE/.env.wp-dev"

export WP_HOST_PORT="$HOST_PORT"

echo "→ Bringing up containers (port $HOST_PORT)"
docker compose up -d db wordpress

echo -n "→ Waiting for WordPress to be healthy"
for _ in $(seq 1 60); do
  status="$(docker compose ps --format json wordpress 2>/dev/null | grep -o '"Health":"[^"]*"' | head -1 || true)"
  if [[ "$status" == *"healthy"* ]]; then
    echo " ✓"
    break
  fi
  echo -n "."
  sleep 2
done

wp() {
  docker compose run --rm -T wp-cli "$@"
}

write_htaccess() {
  # Pass Authorization through Apache so WP Application Passwords reach PHP.
  docker compose exec -T wordpress bash -lc "cat > /var/www/html/.htaccess" <<'EOF'
# BEGIN WordPress
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
# END WordPress
EOF
}

if wp core is-installed 2>/dev/null; then
  echo "→ WP already installed, skipping core install"
else
  echo "→ Installing WordPress"
  wp core install \
    --url="$SITE_URL" \
    --title="Specter WP Dev" \
    --admin_user="$ADMIN_USER" \
    --admin_password="$ADMIN_PASS" \
    --admin_email="$ADMIN_EMAIL" \
    --skip-email
fi

# Pretty permalinks are required for /wp-json/wp/v2/* to return JSON instead
# of redirecting to the HTML home page.
echo "→ Enabling pretty permalinks (required for REST API)"
wp rewrite structure '/%postname%/' --hard >/dev/null
wp rewrite flush --hard >/dev/null
write_htaccess

echo "→ Generating Application Password for $ADMIN_USER"
# --porcelain returns just the password; one fresh password per bootstrap run.
APP_PASSWORD="$(wp user application-password create "$ADMIN_USER" "specter-smoketest-$(date +%s)" --porcelain)"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/wp-dev/bootstrap.sh — do not commit.
WP_SITE_URL=$SITE_URL
WP_USERNAME=$ADMIN_USER
WP_APP_PASSWORD=$APP_PASSWORD
EOF
chmod 600 "$ENV_FILE"

cat <<EOF

✓ WordPress ready at $SITE_URL
  admin login: $ADMIN_USER / $ADMIN_PASS
  credentials written to: $ENV_FILE

Smoke-test the adapter:
  set -a && source $ENV_FILE && set +a
  node bin/ghost-sync.mjs test \\
    --platform wordpress \\
    --site-url "\$WP_SITE_URL" \\
    --username "\$WP_USERNAME" \\
    --app-password "\$WP_APP_PASSWORD"

Tear down:
  npm run wp:down
EOF
